version: "3.8"

services:
  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    depends_on:
      - redis

volumes:
  redis:
  redisinsight:
